name: tunnel_max
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI and Material Design
  cupertino_icons: ^1.0.8
  material_color_utilities: ^0.11.1

  # State Management
  provider: ^6.1.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1

  # Platform Channels and Native Integration
  platform: ^3.1.5

  # Networking and HTTP
  http: ^1.2.2
  dio: ^5.7.0
  connectivity_plus: ^6.0.5

  # JSON Serialization
  json_annotation: ^4.9.0

  # Secure Storage
  flutter_secure_storage: ^9.2.2

  # Cryptography
  crypto: ^3.0.3

  # File System and Path
  path_provider: ^2.1.4
  path: ^1.9.0

  # Logging
  logger: ^2.4.0

  # Utilities
  uuid: ^4.5.1
  intl: ^0.19.0

  # File Operations
  file_picker: ^8.1.2
  share_plus: ^10.0.2

  # Charts and Statistics (for network stats display)
  fl_chart: ^0.69.0

  # URL Launcher
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting and Code Quality
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

  # Testing
  mockito: ^5.4.4

  # Development Tools
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  
  # Android adaptive icon
  adaptive_icon_background: "#2196F3"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"
  
  # Windows icon
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
